<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: flight_operator.proto

namespace FlightOperator;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>SupportChatResponse</code>
 */
class SupportChatResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string customer_support_id = 1;</code>
     */
    protected $customer_support_id = '';
    /**
     * Generated from protobuf field <code>string message = 2;</code>
     */
    protected $message = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $customer_support_id
     *     @type string $message
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\FlightOperator::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string customer_support_id = 1;</code>
     * @return string
     */
    public function getCustomerSupportId()
    {
        return $this->customer_support_id;
    }

    /**
     * Generated from protobuf field <code>string customer_support_id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setCustomerSupportId($var)
    {
        GPBUtil::checkString($var, True);
        $this->customer_support_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string message = 2;</code>
     * @return string
     */
    public function getMessage()
    {
        return $this->message;
    }

    /**
     * Generated from protobuf field <code>string message = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setMessage($var)
    {
        GPBUtil::checkString($var, True);
        $this->message = $var;

        return $this;
    }

}

